name: Check Schemas and Publish GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * 1,4 *"

jobs:
  check_schemas:
    runs-on: ubuntu-latest
    name: Checks for blocking issues

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jsonschema
      - name: Check Schemas
        run: |
          python scripts/check_schemas.py schemas

      - name: Publish GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true

  publish_pages:
    runs-on: ubuntu-latest
    name: Publish GitHub Pages

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json-schema-for-humans jinja2
      - name: Generate schema Sites
        run: |
          mkdir -p site
          generate-schema-doc schemas/ site/
      - name: Generate Index file
        run: |
          python scripts/generate_index.py schemas/

      - name: Publish GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
          clean: true
